name: 'GitHub Action for Codepush - Node v Fix'
author: 'Babalola Oluwaferanmi'
description: 'Wraps the appcenter CLI to enable common commands - fixes node version issue.'
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile'
